# Generated by Django 2.1.15 on 2020-12-01 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('CuNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='课程编号')),
                ('Name', models.CharField(max_length=50, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='homework',
            fields=[
                ('HomNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='作业编号')),
                ('Date', models.CharField(max_length=50, verbose_name='发布日期')),
                ('Cont', models.CharField(max_length=50, verbose_name='作业内容')),
                ('CorAns', models.CharField(max_length=50, verbose_name='作业标准答案')),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('MaNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='管理员编号')),
                ('Name', models.CharField(max_length=50, verbose_name='管理员姓名')),
                ('Sex', models.PositiveSmallIntegerField(null=True, verbose_name='管理员性别')),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('SignNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='签到编号')),
                ('StuNo', models.CharField(max_length=50, verbose_name='学生学号')),
                ('Time', models.DateTimeField(max_length=50, verbose_name='签到时间')),
                ('CuNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.course', verbose_name='课程编号')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('StuNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='学生学号')),
                ('Name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('Sex', models.PositiveSmallIntegerField(null=True, verbose_name='学生性别')),
                ('Major', models.CharField(max_length=50, null=True, verbose_name='学生专业名称')),
                ('CuNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.course', verbose_name='学生选修的课程编号')),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('SubNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='提交编号')),
                ('Ans', models.CharField(max_length=50, null=True, verbose_name='学生答案')),
                ('Score', models.FloatField(verbose_name='作业成绩')),
                ('HomeNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.homework', verbose_name='作业编号')),
                ('StuNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.student', verbose_name='学号')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('TeaNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='教师编号')),
                ('Name', models.CharField(max_length=50, verbose_name='教师姓名')),
                ('Sex', models.PositiveSmallIntegerField(null=True, verbose_name='教师性别')),
                ('SignNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.sign', verbose_name='签到编号')),
            ],
        ),
        migrations.AddField(
            model_name='sign',
            name='TeaNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.teacher', verbose_name='教师编号'),
        ),
        migrations.AddField(
            model_name='homework',
            name='TeaNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.teacher', verbose_name='教师编号'),
        ),
        migrations.AddField(
            model_name='course',
            name='HomeNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.homework', verbose_name='作业编号'),
        ),
        migrations.AddField(
            model_name='course',
            name='TeaNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.teacher', verbose_name='教师编号'),
        ),
    ]
