# Generated by Django 2.1.15 on 2020-12-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20201201_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='Date',
            field=models.DateField(max_length=50, verbose_name='发布日期'),
        ),
    ]
