# Generated by Django 2.1.15 on 2020-12-04 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20201203_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-PubDate']},
        ),
        migrations.RemoveField(
            model_name='homework',
            name='Date',
        ),
        migrations.AddField(
            model_name='homework',
            name='PubDate',
            field=models.DateField(default=django.utils.timezone.now, max_length=50, verbose_name='发布日期'),
        ),
        migrations.AddField(
            model_name='submission',
            name='SubTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='Time',
            field=models.DateTimeField(verbose_name='签到时间'),
        ),
    ]
