# Generated by Django 3.1.4 on 2020-12-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20201206_1856'),
    ]

    operations = [
    ]
