# Generated by Django 2.1.15 on 2020-12-04 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20201204_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='Title',
            field=models.CharField(default='a', max_length=50, verbose_name='作业标题'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='Cont',
            field=models.CharField(max_length=5000, verbose_name='作业内容'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='CorAns',
            field=models.CharField(max_length=5000, verbose_name='作业标准答案'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='HomNo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='作业编号'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='PubDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='发布日期'),
        ),
    ]
