# Generated by Django 3.1.4 on 2020-12-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20201204_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='sign',
            options={'verbose_name': '签到', 'verbose_name_plural': '签到'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
        migrations.RemoveField(
            model_name='manager',
            name='Sex',
        ),
        migrations.AlterField(
            model_name='student',
            name='Sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=30, null=True, verbose_name='学生性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=30, null=True, verbose_name='教师性别'),
        ),
    ]
