# Generated by Django 3.1.4 on 2020-12-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_managertoken_studenttoken_teachertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='MaPassWord',
            field=models.CharField(default='123456', max_length=16, verbose_name='管理员密码'),
        ),
        migrations.AddField(
            model_name='student',
            name='StuPassWord',
            field=models.CharField(default='123456', max_length=16, verbose_name='学生密码'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='TeaPassWord',
            field=models.CharField(default='123456', max_length=16, verbose_name='教师密码'),
        ),
    ]
