# Generated by Django 3.1.4 on 2020-12-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20201204_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='CuNo',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.course', verbose_name='课程编号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='HomeNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.homework', verbose_name='作业编号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='TeaNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.teacher', verbose_name='教师编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='CuNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.course', verbose_name='学生选修的课程编号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='SignNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.sign', verbose_name='签到编号'),
        ),
    ]
