# Generated by Django 3.1.4 on 2020-12-08 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20201206_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('QuesNo', models.IntegerField(primary_key=True, serialize=False, verbose_name='题号')),
                ('Cont', models.CharField(max_length=5000, verbose_name='题目')),
                ('CorAns', models.CharField(max_length=5000, verbose_name='题目答案')),
            ],
            options={
                'ordering': ['-QuesNo'],
            },
        ),
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='token')),
                ('muser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.manager')),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studenttoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachertoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='Cont',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='CorAns',
        ),
        migrations.AddField(
            model_name='student',
            name='need_to_sign',
            field=models.ManyToManyField(related_name='students', to='job.sign'),
        ),
        migrations.AlterField(
            model_name='course',
            name='TeaNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.teacher', verbose_name='教师编号'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='HomNo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='作业id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='CuNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.course', verbose_name='选修的课程编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Major',
            field=models.CharField(max_length=50, null=True, verbose_name='专业名称'),
        ),
        migrations.DeleteModel(
            name='ManagerToken',
        ),
        migrations.DeleteModel(
            name='role',
        ),
        migrations.DeleteModel(
            name='StudentToken',
        ),
        migrations.DeleteModel(
            name='TeacherToken',
        ),
        migrations.AddField(
            model_name='token',
            name='suser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.student'),
        ),
        migrations.AddField(
            model_name='token',
            name='tuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.teacher'),
        ),
        migrations.AddField(
            model_name='question',
            name='HomNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.homework', verbose_name='作业id'),
        ),
    ]
