# Generated by Django 3.1.4 on 2020-12-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20201204_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Name',
            new_name='CuName',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='Name',
            new_name='MaName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='StuName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Sex',
            new_name='StuSex',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Name',
            new_name='TeaName',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Sex',
            new_name='TeaSex',
        ),
    ]
