# Generated by Django 3.1.4 on 2020-12-08 10:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20201208_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-SubTime']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='HomeNo',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='TeaNo',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='TeaNo',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='StuNo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='CuNo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='SignNo',
        ),
        migrations.AddField(
            model_name='course',
            name='StuNo',
            field=models.ManyToManyField(default='1', related_name='courses', to='job.student', verbose_name='选修这门课程的学生学号'),
        ),
        migrations.AddField(
            model_name='homework',
            name='CuNo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='job.course', verbose_name='课程编号'),
        ),
        migrations.AddField(
            model_name='sign',
            name='sign_by',
            field=models.ManyToManyField(default='1', related_name='students', to='job.student', verbose_name='需要进行此签到的学生'),
        ),
        migrations.AlterField(
            model_name='course',
            name='TeaNo',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='job.teacher', verbose_name='上这门课程的教师编号'),
        ),
        migrations.AlterField(
            model_name='question',
            name='HomNo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='job.homework', verbose_name='作业id'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='CuNo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='job.course', verbose_name='课程编号'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='CuNo',
        ),
        migrations.AddField(
            model_name='student',
            name='CuNo',
            field=models.ManyToManyField(default='1', related_name='students', to='job.course', verbose_name='学生选修的课程编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='need_to_sign',
            field=models.ManyToManyField(default='1', related_name='students', to='job.sign', verbose_name='需要进行此次签到的学生'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='HomeNo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='job.homework', verbose_name='作业编号'),
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoticeTitle', models.CharField(default='通知标题', max_length=60, verbose_name='通知标题')),
                ('NoticeContent', models.CharField(default='通知内容', max_length=5000, verbose_name='通知内容')),
                ('NoticePubTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知发布时间')),
                ('MaNo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='job.manager', verbose_name='发布此通知的管理员编号')),
            ],
        ),
    ]
