# Generated by Django 3.1.4 on 2020-12-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20201208_1810'),
    ]

    operations = [
    ]
